.TH "python-coherence-applet" "1" "0.6.2" "Frank Scholz" "Python UPnP Framework"
.SH "NAME"
.LP 
.LP 
Coherence \- Is a Python UPnP framework which enabling your application to
participate in digital living networks, at the moment primarily the
UPnP universe.

Its goal is to relieve your application from all the membership and UPnP
related tasks as much as possible.

The core of Coherence provides a (hopefully complete) implementation
of:
  * a SSDP server,
  * a MSEARCH client,
  * server and client for HTTP/SOAP requests, and
  * server and client for Event Subscription and Notification (GENA).
.SH "OVERVIEW"
.LP 
There are no command line options for applet\-coherence.
.SH "SEE ALSO"
.LP 
coherence 
