#!/bin/bash
input="$1"
output="$2"

# filename must be of the form "movie name.XX[X].srt" or "movie name.srt"
base_name="$(echo $input | sed 's/\..\{2,3\}\.avi$//' | sed 's/\.avi$//')"
srt=$base_name.srt

mencoder "$input" \
-oac lavc -ovc lavc -of mpeg \
-lavcopts vcodec=mpeg2video:keyint=1:vbitrate=200000:vrc_maxrate=9000:vrc_buf_size=1835 \
-vf harddup -mpegopts muxrate=12000 \
-sub "$srt" -font "/usr/share/fonts/truetype/ttf-dejavu/DejaVuSans.ttf" -subfont-autoscale 2 \
-o "$output"

